// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'API_Key',
    appId: '1:322602435499:android:231221897f3eedc9c7c8ee',
    messagingSenderId: '322602435499',
    projectId: 'shaats',
    storageBucket: 'shaats.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS8_8_BKTZE8rdeHlTeLYtdP5ICuQoHQM',
    appId: '1:322602435499:web:7ef3dfe6f3b40787c7c8ee',
    messagingSenderId: '322602435499',
    projectId: 'shaats',
    authDomain: 'shaats.firebaseapp.com',
    storageBucket: 'shaats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvxjhQ16n9gYjdoLf6NmTFMYmwBBRYgxg',
    appId: '1:322602435499:ios:7da5b61a5942ba18c7c8ee',
    messagingSenderId: '322602435499',
    projectId: 'shaats',
    storageBucket: 'shaats.firebasestorage.app',
    iosBundleId: 'com.example.shaats',
  );

}